name: Deploy Vibrex App on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x] # Changed from 22.x to 20.x for stability

    steps:
      # ------------------------------
      # CHECKOUT CODE
      # ------------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: |
            VibrexBackend/package-lock.json
            Vibrex/package-lock.json

      # ------------------------------
      # BACKEND SETUP
      # ------------------------------
      - name: Install backend dependencies
        working-directory: ./VibrexBackend
        run: npm install

      - name: Create backend .env file
        working-directory: ./VibrexBackend
        run: |
          touch .env
          echo "${{ secrets.PROD_BACKEND_ENV }}" > .env

      - name: Restart backend with PM2
        working-directory: ./VibrexBackend
        run: |
          /home/ubuntu/.nvm/versions/node/v22.21.0/bin/pm2 delete vibrex-backend || true
          /home/ubuntu/.nvm/versions/node/v22.21.0/bin/pm2 start index.js --name vibrex-backend
          /home/ubuntu/.nvm/versions/node/v22.21.0/bin/pm2 save

      # ------------------------------
      # FRONTEND SETUP
      # ------------------------------
      - name: Cache frontend dependencies
        uses: actions/cache@v3
        with:
          path: Vibrex/node_modules
          key: frontend-${{ hashFiles('Vibrex/package-lock.json') }}
          restore-keys: frontend-

      - name: Install frontend dependencies
        working-directory: ./Vibrex
        run: npm ci

      - name: Create frontend .env file
        working-directory: ./Vibrex
        run: |
          echo "${{ secrets.PROD_FRONTEND_ENV }}" > .env

      - name: Build frontend
        working-directory: ./Vibrex
        run: NODE_OPTIONS="--max-old-space-size=4096" npm run build

      - name: Deploy frontend to Nginx
        working-directory: ./Vibrex
        run: |
          echo "Checking dist folder..."
          ls -la dist/
          sudo rsync -av --delete dist/ /var/www/html/
